### ISSUE TITLE
.dispose() cancela la ejecución

### ISSUE THREAD

**Issue by lesclaz** [m4gen/simple#1]
https://github.com/m4gen/simple/blob/6f8b758bacdd892231442f7612694b64df831bee/app/src/main/java/com/arr/simple/ui/nauta/CaptiveNautaFragment.java#L37-L51

Debes eliminar la linea 50 (.dispose()), ya que al parecer esto cancela la ejecución del código. Esta es la respuesta que me dio chatGPT:

> El fragmento de código que has compartido parece ser parte de una implementación en Java que utiliza RxJava o una librería similar para manejo asíncrono de llamadas. La llamada `getCaptcha()` se suscribe a un `Observable` para manejar la respuesta asíncrona.

> El problema principal en este fragmento es la llamada a `.dispose()` inmediatamente después de suscribirse al `Observable`. El método `dispose()` se utiliza para liberar los recursos o cancelar la subscripción asociada a este `Observable`, lo que significa que el `Observable` se cancela antes de que tenga la oportunidad de emitir cualquier item o notificación, incluyendo la respuesta del servidor o un error.

> Para solucionar este problema, debes evitar llamar a `dispose()` inmediatamente. En su lugar, debes mantener una referencia al `Disposable` retornado por el método `subscribe()` y llamar a `dispose()` en un momento adecuado para evitar fugas de memoria, por ejemplo, cuando la actividad o el fragmento se destruya o ya no necesites la respuesta.

> Aquí tienes una versión corregida del método que guarda la referencia del `Disposable` y evita llamar a `dispose()` inmediatamente:

> ```java
>
> private Disposable disposable;
> 
> private void obtainCaptcha() { 
>     disposable = service.getCaptcha() 
>         .subscribe( 
>             response -> { 
>                 idRequest = response.getIdRequest(); 
>                 String captchaContent = response.getData(); 
> 
>                 System.out.print("Captcha: " + captchaContent); 
>                 Log.i("Captcha: ", captchaContent); 
>             }, 
>             throwable -> { 
>                 throw new RuntimeException(throwable); 
>             }
>         ); 
> }
> 
> @Override
> protected void onDestroy() {
>     super.onDestroy();
>     if (disposable != null && !disposable.isDisposed()) {
>         disposable.dispose();
>     }
> }
> ```
> 
> En este código, he añadido un campo `Disposable disposable` para mantener la referencia al `Disposable` retornado por `subscribe()`. Luego, he agregado un método `onDestroy()` como ejemplo de dónde podrías llamar a `dispose()` para liberar recursos cuando ya no sean necesarios, asumiendo que este código está dentro de una clase que tiene un ciclo de vida similar al de una actividad o fragmento en Android.
> 
> Recuerda ajustar el manejo de `dispose()` basado en el ciclo de vida del componente que estás utilizando (por ejemplo, una actividad, fragmento, o cualquier otro tipo de objeto con un ciclo de vida claro en tu aplicación).

**Comment by m4gen** [comment]
ya, después de haber quitado `dispose()` si se hace la petición al servidor y se devuelve como respuesta 

```HTML
<svg xmlns="http://www.w3.org/2000/svg" width="250" height="60" viewBox="0,0,250,60"><rect width="100%" height="100%" fill="#cc9966"/><path fill="#3f3c3b" d="M24.33 15.87C24.11 15.75 24.08 15.83.......

```

muchas gracias.

**Comment by m4gen** [comment]
> ya, después de haber quitado `dispose()`si se hace la petición al servidor y se devuelve como respuesta
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" width="250" height="60" viewBox="0,0,250,60"><rect width="100%" height="100%" fill="#cc9966"/><path fill="#3f3c3b" d="M24.33 15.87C24.11 15.75 24.08 15.83.......
> ```
> 
> muchas gracias.

Ahora a las demás solicitudes como
```java 
request = new LoginRequest(usuario, password, "USUARIO_PORTAL", idRequest, captcha);
   service.login(request)....
```

 también debería eliminar `dispose()` ?

**Comment by lesclaz** [comment]
Si, de lo contrario de destruye la ejecución de la petición antes de finalizar.

**Comment by m4gen** [comment]
> Si, de lo contrario de destruye la ejecución de la petición antes de finalizar.

he agregado en [CaptiveNautaFragment.java](https://github.com/m4gen/simple/blob/6f8b758bacdd892231442f7612694b64df831bee/app/src/main/java/com/arr/simple/ui/nauta/CaptiveNautaFragment.java)

```java 
private void accessToNauta(String usuario, String password, String captcha) {
        request = new LoginRequest(usuario, password, "USUARIO_PORTAL", idRequest, captcha);
        disposable =
                service.login(request)
                        .subscribe(
                                response -> {
                                    Log.e("LOGIN ", response.getResult());
                                    if (response.getResult().equals("ok")) {
                                        Log.i("Response Login ", response.getUser().toString());

                                        ((User) response.getUser())
                                                .getServices()
                                                .getMobileServices()
                                                .forEach(this::requestInfoMobile);
                                    }
                                },
                                throwable -> {
                                    if (throwable instanceof Exception e) {
                                        showToast(e.getMessage());
                                    }
                                });
    }
```
pero una vez rellenado los datos (Usuario, password y código captcha) y presionado conectar, no recibo respuesta, agregue un `Log` antes y después de la comprobación de si result es "ok" y no recibo ningún Log, es como si el código no llegase a ejecutarse nunca. 

ya probé sin `Disposable` y tampoco se ejecuta.

**Comment by lesclaz** [comment]
¿Tampoco te muestra el toast?
A lo mejor le envías mal los datos de inicio de sesión. Ejemplo: el username, si es un número de teléfono debe tener el formato +535XXXXXXX.
Por otro lado, si estás en el apartado de información de cuentas nauta, deberías obtener los servicios de navegación (navServices) en ves de los móviles (mobileServices).

**Comment by lesclaz** [comment]
Por otro lado. Si lo que buscas es iniciar sesión en internet con nauta hogar o en parques wifi, debes usar 'AccessClient' que usa el portal https://secure.etecsa.net:8443/.

PortalAuthServiceRx es un cliente para https://www.nauta.cu/ no se si me explico.

**Comment by m4gen** [comment]
> ¿Tampoco te muestra el toast? A lo mejor le envías mal los datos de inicio de sesión. Ejemplo: el username, si es un número de teléfono debe tener el formato +535XXXXXXX. Por otro lado, si estás en el apartado de información de cuentas nauta, deberías obtener los servicios de navegación (getNavServices) en ves de los móviles (getMobileServices).

no agregué el +53 delante, probaré a ver si ese es el problema, por cierto se puede iniciar tanto con el número como con el correo @nauta.cu en el caso de los usuarios que se hayan registrado así?

**Comment by lesclaz** [comment]
> no agregué el +53 delante, probaré a ver si ese es el problema, por cierto se puede iniciar tanto con el número como con el correo @nauta.cu en el caso de los usuarios que se hayan registrado así?

si

**Comment by m4gen** [comment]
ya el error fue mio que puse los String de los datos obtenidos de los EditText fuera del onClickListener y devolvía los datos en blanco.

ya todo está trabajando bien, gracias por la ayuda y disculpa tanta jodedera jajjajaja. 

saludos
